/*
 * CatchKit
 * Single header - Generated: 2025-12-20 12:44:07.078292
 * ----------------------------------------------------------
 * This file has been generated by merging together multiple source files.
 * Please don't edit it directly.
 *
 * Distributed under the MIT license. See text reproduced, below:
 *
 * Copyright 2025 Phil Nash
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the “Software”), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
 */
#ifndef CATCHKIT_PACKED_H_INCLUDED
#define CATCHKIT_PACKED_H_INCLUDED

// Packed header

// System includes (for headers):
#include <bit>
#include <cassert>
#include <cmath>
#include <exception>
#include <format>
#include <ranges>
#include <set>
#include <source_location>
#include <sstream>
#include <string>
#include <string_view>
#include <type_traits>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

// From header files:

// Packed from catchkit/include/catchkit/result_type.h
namespace CatchKit {

    enum class ResultType {
        Failed = 0,
        Passed = 1
    };

    inline bool operator! (ResultType result) {
        return result == ResultType::Failed;
    }

} // namespace CatchKit


// Packed from catchkit/include/catchkit/expression_info.h
namespace CatchKit {

    struct SubExpressionInfo {
        std::string description;
        bool result;
    };


    struct UnaryExpressionInfo {
        std::string value;
    };
    struct BinaryExpressionInfo {
        std::string lhs;
        std::string rhs;

        std::string_view op;
    };
    struct MatchExpressionInfo {
        std::string candidate_value;
        std::string matcher;

        std::vector<SubExpressionInfo> sub_expressions;
    };
    struct ExceptionExpressionInfo {
        std::string exception_message;
        enum class Type { Expected, Unexpected, Missing };
        Type type;
    };
    struct ExpectationExpressionInfo {
        // !TBD
    };

    using ExpressionInfo = std::variant<
        std::monostate,
        UnaryExpressionInfo,
        BinaryExpressionInfo,
        MatchExpressionInfo,
        ExceptionExpressionInfo,
        ExpectationExpressionInfo>;

} // namespace CatchKit

template<>
struct std::formatter<CatchKit::ExpressionInfo> {
    [[nodiscard]] constexpr static auto parse(std::format_parse_context const& ctx) { return ctx.begin(); }
    static std::format_context::iterator format(CatchKit::ExpressionInfo const& expr, std::format_context& ctx);
};


// Packed from catchkit/include/catchkit/report_on.h
namespace CatchKit {

    enum class ReportOn {
        Nothing = 0,
        PassingTests = 1,
        FailingTests = 2,
        AllResults = PassingTests | FailingTests,
    };

    constexpr ReportOn operator&(ReportOn lhs, ReportOn rhs) {
        return static_cast<ReportOn>(
            static_cast<std::underlying_type_t<ReportOn>>(lhs) &
            static_cast<std::underlying_type_t<ReportOn>>(rhs)
        );
    }
    inline bool report_on_passing(ReportOn report_on) {
        return (report_on & ReportOn::PassingTests) == ReportOn::PassingTests;
    }
    inline bool report_on_failing(ReportOn report_on) {
        return (report_on & ReportOn::FailingTests) == ReportOn::FailingTests;
    }

} // namespace CatchKit


// Packed from catchkit/include/catchkit/result_handler.h
namespace CatchKit::Detail
{
    struct AssertionContext;
    struct VariableCaptureRef;

    enum class ResultDisposition { Abort, Continue };
    enum class ResultDetailNeeded { Yes, No };

    struct ResultHandler {
        ReportOn report_on;

        explicit ResultHandler(ReportOn report_on) : report_on(report_on) {}
        virtual ~ResultHandler();

        virtual void on_assertion_start( ResultDisposition result_disposition, AssertionContext const& context ) = 0;
        [[nodiscard]] virtual auto on_assertion_result( ResultType result ) -> ResultDetailNeeded = 0;
        virtual void on_assertion_result_detail( ExpressionInfo const& expression_info, std::string_view message ) = 0;
        virtual void on_assertion_end() = 0;

        virtual void add_variable_capture(VariableCaptureRef*) { /* do nothing by default */ };
        virtual void remove_variable_capture(VariableCaptureRef*) { /* do nothing by default */ };

    };

} // namespace CatchKit::Detail

namespace CatchKit
{
    using Detail::ResultDisposition;
}


// Packed from catchkit/include/catchkit/assertion_context.h
namespace CatchKit::Detail {

    struct AssertionContext {
        std::string_view macro_name;
        std::string_view original_expression;
        std::string_view message  = {};
        std::source_location location = std::source_location::current();
    };

} // namespace CatchKit::Detail

namespace CatchKit {

    using Detail::AssertionContext;

} // namespace CatchKit


// Packed from catchkit/include/catchkit/assert_result_handler.h
namespace CatchKit::Detail {

    struct AssertResultHandler final : ResultHandler {
        AssertionContext current_context;
        ResultType last_result = ResultType::Passed;
        ResultDisposition current_result_disposition = ResultDisposition::Abort;

        AssertResultHandler() : ResultHandler(ReportOn::FailingTests) {}

        void on_assertion_start( ResultDisposition result_disposition, AssertionContext const& context ) override;
        [[nodiscard]] auto on_assertion_result( ResultType result ) -> ResultDetailNeeded override;
        void on_assertion_result_detail( ExpressionInfo const& expression_info, std::string_view message ) override;
        void on_assertion_end() override;
    };

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/captured_variable.h
namespace CatchKit {

    struct CapturedVariable {
        std::string name;
        std::string type;
        std::string value;
    };

} // namespace CatchKit


// Packed from catchkit/include/catchkit/operators.h
namespace CatchKit::Detail {

    enum class Operators {
        None,
        Equals,
        NotEqualTo,
        GreaterThan,
        LessThan,
        GreaterThanOrEqual,
        LessThanOrEqual
    };

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/expr_ref.h
namespace CatchKit::Detail {

    // Holds binary expression
    template<typename LhsT, typename RhsT, Operators Op>
    struct BinaryExprRef {
        LhsT& lhs;
        RhsT& rhs;

        [[nodiscard]] auto evaluate() const -> ResultType;
        [[nodiscard]] auto expand( ResultType result ) const -> ExpressionInfo;

    };

    // Holds a unary expression - ie just evaluates to a single value
    // Also used for the LHS of a binary expression during decomposition
    template<typename T>
    struct UnaryExprRef {
        T& value;

        [[nodiscard]] auto evaluate() const -> ResultType;
        [[nodiscard]] auto expand( ResultType result ) const -> ExpressionInfo;

        template<Operators Op, typename RhsT>
        auto make_binary_expr( RhsT&& rhs ) noexcept { // NOSONAR (ref is used within its lifetime) NOLINT (misc-typo)
            return BinaryExprRef<T, std::remove_reference_t<RhsT>, Op>{ value, rhs };
        }

        template<typename RhsT>
        [[maybe_unused]] friend auto operator == ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( !(std::is_pointer_v<T> && !std::is_pointer_v<RhsT> && std::is_integral_v<RhsT>),
                "Comparing pointers against integrals (even 0) is not supported. Do you mean to use nullptr?");
            static_assert( requires{ lhs.value == rhs; } );
            return lhs.template make_binary_expr<Operators::Equals>( std::forward<RhsT>( rhs ) );
        }
        template<typename RhsT>
        [[maybe_unused]] friend auto operator != ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( !(std::is_pointer_v<T> && !std::is_pointer_v<RhsT> && std::is_integral_v<RhsT>),
                "Comparing pointers against integrals (even 0) is not supported. Do you mean to use nullptr?");
            static_assert( requires{ lhs.value != rhs; } );
            return lhs.template make_binary_expr<Operators::NotEqualTo>( std::forward<RhsT>( rhs ) );
        }
        template<typename RhsT>
        [[maybe_unused]] friend auto operator < ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( requires{ lhs.value < rhs; } );
            return lhs.template make_binary_expr<Operators::LessThan>( std::forward<RhsT>( rhs ) );
        }
        template<typename RhsT>
        [[maybe_unused]] friend auto operator > ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( requires{ lhs.value > rhs; } );
            return lhs.template make_binary_expr<Operators::GreaterThan>( std::forward<RhsT>( rhs ) );
        }
        template<typename RhsT>
        [[maybe_unused]] friend auto operator <= ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( requires{ lhs.value <= rhs; } );
            return lhs.template make_binary_expr<Operators::LessThanOrEqual>( std::forward<RhsT>( rhs ) );
        }
        template<typename RhsT>
        [[maybe_unused]] friend auto operator >= ( UnaryExprRef lhs, RhsT&& rhs ) noexcept {
            static_assert( requires{ lhs.value >= rhs; } );
            return lhs.template make_binary_expr<Operators::GreaterThanOrEqual>( std::forward<RhsT>( rhs ) );
        }
    };

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/internal_compilers.h
#if defined(__clang__)
#  define CATCHKIT_COMPILER_CLANG
#elif defined(__GNUC__) && !defined(__ICC) && !defined(__CUDACC__) // GCC
#  define CATCHKIT_COMPILER_GCC
#  define CATCHKIT_GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#elif define(_MSC_VER)
#  define CATCHKIT_COMPILER_MSVC
#else
#  define CATCHKIT_COMPILER_OTHER
#endif


// Packed from catchkit/include/catchkit/internal_macro_utils.h
#define CATCHKIT_INTERNAL_STRINGIFY_ARGS(...) #__VA_ARGS__

// Generate a unique name, given a root
#define CATCHKIT_INTERNAL_UNIQUE_NAME_CAT2( first, second ) first##second
#define CATCHKIT_INTERNAL_UNIQUE_NAME_CAT( first, second ) CATCHKIT_INTERNAL_UNIQUE_NAME_CAT2( first, second )
#define CATCHKIT_INTERNAL_UNIQUE_NAME( name ) CATCHKIT_INTERNAL_UNIQUE_NAME_CAT( name, __LINE__ )

// Split list of args into head and tail
#define CATCHKIT_VA_MACRO_HEAD(first, ...) first
#define CATCHKIT_VA_MACRO_TAIL(first, ...) __VA_ARGS__


// Packed from catchkit/include/catchkit/internal_warnings.h
#ifdef CATCHKIT_COMPILER_CLANG
#  define CATCHKIT_CLANG_PRAGMA(w) _Pragma(w)
#  define CATCHKIT_CLANG_PRAGMA_NO_TOOLS(w) _Pragma(w) // used for push/ pop - not defined for other compilers
#  define CATCHKIT_GCC_PRAGMA(w)
#  define CATCHKIT_MSVC_PRAGMA(w)

#elifdef CATCHKIT_COMPILER_GCC
#  if CATCHKIT_GCC_VERSION < 150300
#    define CATCHKIT_CLANG_PRAGMA(w)
#  else
#    define CATCHKIT_CLANG_PRAGMA(w) _Pragma(w) // Invoked for clang tools, regardless of compiler
#  endif
#  define CATCHKIT_CLANG_PRAGMA_NO_TOOLS(w)
#  define CATCHKIT_GCC_PRAGMA(w) _Pragma(w)
#  define CATCHKIT_MSVC_PRAGMA(w)

#elifdef CATCHKIT_COMPILER_MSVC
#  define CATCHKIT_CLANG_PRAGMA(w)
#  define CATCHKIT_CLANG_PRAGMA_NO_TOOLS(w)
#  define CATCHKIT_GCC_PRAGMA(w)
#  define CATCHKIT_MSVC_PRAGMA(w) __pragma(w)

#else
#  define CATCHKIT_CLANG_PRAGMA(w)
#  define CATCHKIT_CLANG_PRAGMA_NO_TOOLS(w)
#  define CATCHKIT_GCC_PRAGMA(w)
#  define CATCHKIT_MSVC_PRAGMA(w)
#endif

#define CATCHKIT_CLANG_WARNING_UNSCOPED_DISABLE(w) CATCHKIT_CLANG_PRAGMA_NO_TOOLS( CATCHKIT_INTERNAL_STRINGIFY_ARGS(clang diagnostic ignored w) )
#define CATCHKIT_CLANG_WARNING_DISABLE(w) CATCHKIT_CLANG_PRAGMA( CATCHKIT_INTERNAL_STRINGIFY_ARGS(clang diagnostic ignored w) )
#define CATCHKIT_GCC_WARNING_DISABLE(w) CATCHKIT_GCC_PRAGMA( CATCHKIT_INTERNAL_STRINGIFY_ARGS(GCC diagnostic ignored w) )
#define CATCHKIT_MSVC_WARNING_DISABLE(w) CATCHKIT_MSVC_PRAGMA( warning( disable:w ) )

// Start warning suppression block >>>
#define CATCHKIT_WARNINGS_SUPPRESS_START \
    CATCHKIT_GCC_PRAGMA( "GCC diagnostic push" ) \
    CATCHKIT_GCC_PRAGMA( "GCC diagnostic ignored \"-Wunknown-pragmas\"") \
    CATCHKIT_CLANG_PRAGMA_NO_TOOLS( "clang diagnostic push" ) \
    CATCHKIT_MSVC_PRAGMA ( warning(push) )

// End warning suppression block <<<
#define CATCHKIT_WARNINGS_SUPPRESS_END \
    CATCHKIT_CLANG_PRAGMA_NO_TOOLS( "clang diagnostic pop" ) \
    CATCHKIT_GCC_PRAGMA( "GCC diagnostic pop" ) \
    CATCHKIT_MSVC_PRAGMA( warning(pop) )


#define CATCHKIT_WARNINGS_SUPPRESS_PARENTHESES \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wparentheses" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wparentheses" )

#define CATCHKIT_WARNINGS_SUPPRESS_UNUSED_COMPARISON \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wunused-comparison" )

#define CATCHKIT_WARNINGS_SUPPRESS_ADDRESS \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Waddress" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Waddress" )

#define CATCHKIT_WARNINGS_SUPPRESS_SIGN_MISMATCH \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wsign-compare" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wsign-compare" ) \
    CATCHKIT_MSVC_WARNING_DISABLE( 4389 ) /* 'equality-operator' : signed/unsigned mismatch */ \
    CATCHKIT_MSVC_WARNING_DISABLE( 4018 ) /* 'token' : signed/unsigned mismatch */

#define CATCHKIT_WARNINGS_SUPPRESS_UNUSED_PARAMETER \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wunused-parameter" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wunused-parameter" )

#define CATCHKIT_WARNINGS_UNSCOPED_SUPPRESS_UNUSED_PARAMETER \
    CATCHKIT_CLANG_WARNING_UNSCOPED_DISABLE( "-Wunused-parameter" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wunused-parameter" )

#define CATCHKIT_WARNINGS_SUPPRESS_FLOAT_RANGE \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wliteral-range" )

#define CATCHKIT_WARNINGS_SUPPRESS_NULL_CONVERSION \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wnull-conversion" )

#define CATCHKIT_WARNINGS_SUPPRESS_SHADOW \
    CATCHKIT_CLANG_WARNING_DISABLE( "-Wshadow" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wshadow" )

#define CATCHKIT_WARNINGS_UNSCOPED_SUPPRESS_SHADOW \
    CATCHKIT_CLANG_WARNING_UNSCOPED_DISABLE( "-Wshadow" ) \
    CATCHKIT_GCC_WARNING_DISABLE  ( "-Wshadow" )



// Packed from catchkit/include/catchkit/operator_to_string.h
namespace CatchKit::Detail {

    // String conversions for operator enum
    template<Operators op>
    [[nodiscard]] consteval auto operator_to_string() noexcept
    {
        using enum Operators;
        if constexpr( op == Equals )                    return "==";
        else if constexpr( op == NotEqualTo )           return "!=" ;
        else if constexpr( op == GreaterThan )          return ">";
        else if constexpr( op == LessThan )             return "<";
        else if constexpr( op == GreaterThanOrEqual )   return ">=";
        else if constexpr( op == LessThanOrEqual )      return "<=";
        else {
            // Note that while None is a valid enum value, we should never use it on a path that leads here
            static_assert( false, "Unrecognised operator" );
        }
    }

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/exceptions.h
namespace CatchKit::Detail {

    extern const std::string unknown_exception_message;

    [[nodiscard]] auto get_current_exception_message() -> std::string;

    [[nodiscard]] auto get_exception_message( std::exception_ptr const& ex ) -> std::string;
    [[nodiscard]] auto get_exception_message( std::exception const& ex ) -> std::string;
    [[nodiscard]] auto get_exception_message( std::string const& str ) -> std::string;

    [[nodiscard]] inline auto get_exception_message(...) -> std::string { // NOSONAR NOLINT (misc-typo)
        return unknown_exception_message;
    }

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/reflection.h
namespace CatchKit {
    namespace Detail {
        auto parse_templated_name( std::string const& templated_name, std::source_location location = std::source_location::current() ) -> std::string_view;
        template<typename T>
        auto type_to_string() -> std::string_view {
            // Handle common built-in types directly to save instantiating a std::source_location
            if constexpr( std::is_same_v<T, int> )
                return "int";
            if constexpr( std::is_same_v<T, bool> )
                return "bool";
            if constexpr( std::is_same_v<T, float> )
                return "float";
            if constexpr( std::is_same_v<T, double> )
                return "double";
            if constexpr( std::is_same_v<T, std::string> )
                return "std::string";
            if constexpr( std::is_same_v<T, std::string_view> )
                return "std::string_view";
            else
                return parse_templated_name("T");
        }
        auto normalise_type_name(std::string_view type_name) -> std::string;

        // Converts this compile-time known enum case to a string
        template<auto EC>
        consteval auto enum_case_to_string() -> std::string_view {
            std::string_view fname = std::source_location::current().function_name();
            if( auto start = fname.find("EC = "); start != std::string_view::npos ) {
                start += 5;
                auto end = fname.find_first_of(";]", start);
                assert( end != std::string_view::npos ); // If a compiler error leads here we need to fix the parsing
                return fname.substr(start, end-start);
            }
            return {};
        }
        consteval auto is_valid_enum_case(std::string_view name) -> bool {
            return !name.empty() && name[0] != '(';
        }

        auto unknown_enum_to_string(std::integral auto enum_value) -> std::string {
            return std::format("<unknown enum value: {}>", enum_value);
        }
        auto remove_qualification(std::string_view qualified_name) -> std::string_view;

        constexpr int enum_probe_start = 0;
        constexpr int enum_sparse_probe_end = 16;
        constexpr int enum_sequential_probe_end = 64;

        template<typename E,
            int direction,
            int probe,
            int sparse_probe_end,
            int sequential_probe_end>
        struct enum_value_string {
            using UnderlyingType = std::underlying_type_t<E>;
            static constexpr UnderlyingType candidate = static_cast<UnderlyingType>(probe*direction);
            static constexpr auto find(E value) -> std::string_view { return find(std::to_underlying(value)); }
            static constexpr auto find(UnderlyingType underlying) -> std::string_view {
                if constexpr( requires { std::integral_constant<E, static_cast<E>( candidate )>{}; } ) {
                    constexpr auto case_name = enum_case_to_string<static_cast<E>( candidate )>();
                    if( underlying == candidate )
                        return remove_qualification( case_name );
                    if constexpr( ( probe < sparse_probe_end || is_valid_enum_case( case_name ) )
                            && probe <sequential_probe_end ) {
                        return enum_value_string<E, direction, probe+1, sparse_probe_end, sequential_probe_end>::find(underlying);
                    }
                }
                return {};
            }
        };

        // Convert a runtime enum case value to a string
        template<
                int sparse_probe_end=enum_sparse_probe_end,
                int sequential_probe_end=enum_sequential_probe_end,
                int probe_start=enum_probe_start,
                typename E>
            requires std::is_enum_v<E>
        auto constexpr probed_enum_to_string(E e) -> std::string {
            auto underlying = std::to_underlying(e);
            if constexpr( std::is_signed_v<std::underlying_type_t<E>> ) {
                if( underlying < 0 )
                    if( auto name = enum_value_string<E, -1, probe_start+1, sparse_probe_end, sequential_probe_end>::find(e); !name.empty() )
                        return std::string(name);
            }
            if( auto name = enum_value_string<E, 1, probe_start, sparse_probe_end, sequential_probe_end>::find(e); !name.empty() )
                return std::string(name);
            return unknown_enum_to_string( underlying );
        }

    } // namespace Detail

    using Detail::type_to_string;
    using Detail::probed_enum_to_string; // Lets you specify the probe parameters

    // Convert a runtime enum case value to a string
    template<typename E> requires std::is_enum_v<E>
    auto constexpr enum_to_string(E e) -> std::string {
        return Detail::probed_enum_to_string(e);
    }

} // namespace CatchKit


// Packed from catchkit/include/catchkit/stringify.h
#ifdef CATCHKIT_FALLBACK_TO_OSTREAM_STRING_CONVERSIONS
#include <sstream>
#endif

namespace CatchKit {

    auto pointer_to_string(std::uintptr_t p) -> std::string;

    inline auto pointer_to_string(void const* p) -> std::string {
        return pointer_to_string(std::bit_cast<std::uintptr_t>(p));
    }

    auto function_pointer_to_string(auto p) -> std::string {
        return pointer_to_string(std::bit_cast<std::uintptr_t>(p));
    }
    auto member_pointer_to_string(void const* p, std::size_t size) -> std::string;

    template<typename T>
    auto member_pointer_to_string(T mp) -> std::string {
        return member_pointer_to_string(&mp, sizeof(T));
    }

    // Specialise this with a stringify member function for your own conversions
    template<typename T>
    struct Stringifier;

    template<typename T>
    concept Stringifiable = requires { Stringifier<T>::stringify; };

    template<typename T>
    [[nodiscard]] auto constexpr stringify(T const& value );
}

// This allows any type for which there is a Stringifier specialisation to be usable by std::format.
// This is necessary so that ranges/ containers of custom types will work.
// Note that if you provide both a std::formatter _and_ a Stringifier for your types,
// then stringified _containers_ (or ranges) of them will prefer the std::formatter specialisations.
template<CatchKit::Stringifiable T>
struct std::formatter<T> { // NOLINT
    constexpr static auto parse( std::format_parse_context const& ctx ) { return ctx.begin(); }
    auto format(T const& val, auto& ctx) const {
        return std::format_to( ctx.out(), "{}", CatchKit::Stringifier<T>::stringify(val) );
    }
};

namespace CatchKit {
#ifdef FALLBACK_TO_OSTREAM_STRING_CONVERSIONS
    template <typename T>
    concept Streamable = requires( std::ostream os, T value ) {
        { os << value };
    };
#endif

    // Don't specialise this, specialise Stringifier instead
    template<typename T>
    [[nodiscard]] auto constexpr stringify(T const& value ) {
        if constexpr( std::is_enum_v<T> )
            return enum_to_string( value );
        else if constexpr( std::is_null_pointer_v<T> )
            return std::string("nullptr");
        else if constexpr( std::is_pointer_v<T> ) {
            if( !value )
                return std::string("nullptr");
            if constexpr( std::is_convertible_v<T, char const*> )
                return std::format("\"{}\"", value);
            else if constexpr (std::is_function_v<std::remove_pointer_t<T>>)
                return function_pointer_to_string(value);
            else
                return pointer_to_string( value );
        }
        else if constexpr( std::is_convertible_v<T, std::string> )
            return std::format("\"{}\"", value);
        else if constexpr( std::formattable<T, char> )
            return std::format("{}", value);
#ifdef FALLBACK_TO_OSTREAM_STRING_CONVERSIONS
        else if constexpr ( Streamable<T> ) {
            std::ostringstream oss;
            oss << value;
            return oss.str();
        }
#endif
        else if constexpr (std::is_function_v<T>)
            return function_pointer_to_string( &value );
        else if constexpr( std::is_member_pointer_v<T> )
            return member_pointer_to_string( value );
        else
            return std::format( "{}(?)", type_to_string<T>() );
    }

} // namespace CatchKit


// Packed from catchkit/include/catchkit/variable_capture_ref.h
namespace CatchKit::Detail
{
    struct Checker;
    struct ResultHandler;

    struct VariableCaptureRef {
        std::string_view name;
        std::string_view type;
        ResultHandler& result_handler;

        [[nodiscard]] virtual auto get_value() const -> std::string = 0;

    protected:
        VariableCaptureRef(std::string_view name, std::string_view type, Checker& checker);
        ~VariableCaptureRef(); // not virtual because we never destroy polymorphically
    };

    template<typename T>
    struct TypedVariableCaptureRef final : VariableCaptureRef {
        T const& value;

        [[nodiscard]] auto get_value() const -> std::string override { return stringify( value ); }

        TypedVariableCaptureRef(T const& value, std::string_view name, Checker& checker)
        :   VariableCaptureRef( name, type_to_string<T>(), checker ),
            value(value)
        {}
    };

} // namespace CatchKit::Detail


// Packed from catchkit/include/catchkit/macros.h
#define CATCHKIT_INTERNAL_ASSERT(macro_name, checker_fun, invert_result, ...) \
    checker.checker_fun( CatchKit::AssertionContext(macro_name, #__VA_ARGS__), invert_result ) \
        .handle_unexpected_exceptions([&](CatchKit::Detail::Asserter& asserter){ \
            if( checker.should_decompose ) { \
                CATCHKIT_WARNINGS_SUPPRESS_START \
                CATCHKIT_WARNINGS_SUPPRESS_UNUSED_COMPARISON \
                asserter.accept_expr( asserter <=> __VA_ARGS__ ); \
                CATCHKIT_WARNINGS_SUPPRESS_END \
            } else { \
                asserter.simple_assert(__VA_ARGS__); \
            } \
        })

#define CATCHKIT_INTERNAL_ASSERT_THAT(macro_name, checker_fun, arg, match_expr) \
    checker.checker_fun( CatchKit::AssertionContext(macro_name, #arg ", " #match_expr) ) \
        .handle_unexpected_exceptions([&](CatchKit::Detail::Asserter& asserter){ \
            using namespace CatchKit::Matchers; \
            asserter.assert_that( [&]{ return arg; }, match_expr ); \
        })

#define CATCHKIT_INTERNAL_BOOL_ASSERT(macro_name, checker_fun, pass) \
    checker.checker_fun( CatchKit::AssertionContext(macro_name, {} ) ) \
        .handle_unexpected_exceptions([&](CatchKit::Detail::Asserter& asserter){ \
            asserter.simple_assert( pass ); \
        })

#define CHECK(...) CATCHKIT_INTERNAL_ASSERT( "CHECK", check, CatchKit::Detail::InvertResult::No, __VA_ARGS__ )
#define REQUIRE(...) CATCHKIT_INTERNAL_ASSERT( "REQUIRE", require, CatchKit::Detail::InvertResult::No, __VA_ARGS__ )

#define CHECK_THAT( arg, matcher ) CATCHKIT_INTERNAL_ASSERT_THAT( "CHECK_THAT", check, arg, matcher )
#define REQUIRE_THAT( arg, matcher ) CATCHKIT_INTERNAL_ASSERT_THAT( "REQUIRE_THAT", require, arg, matcher )

#define CHECK_FALSE(...) CATCHKIT_INTERNAL_ASSERT( "CHECK_FALSE", check, CatchKit::Detail::InvertResult::Yes, __VA_ARGS__ )
#define REQUIRE_FALSE(...) CATCHKIT_INTERNAL_ASSERT( "REQUIRE_FALSE", require, CatchKit::Detail::InvertResult::Yes, __VA_ARGS__ )

// Variable capture
#define CATCHKIT_INTERNAL_DECLARE_VAR_X(suffix, var) CatchKit::Detail::TypedVariableCaptureRef CATCHKIT_INTERNAL_UNIQUE_NAME(var_capture##suffix)(var, #var, checker)

#define CATCHKIT_INTERNAL_DECLARE_VARS_1(a) CATCHKIT_INTERNAL_DECLARE_VAR_X(_1, a)
#define CATCHKIT_INTERNAL_DECLARE_VARS_2(a, b) CATCHKIT_INTERNAL_DECLARE_VAR_X(_1, a); CATCHKIT_INTERNAL_DECLARE_VAR_X(_2, b)
#define CATCHKIT_INTERNAL_DECLARE_VARS_3(a, b, c) CATCHKIT_INTERNAL_DECLARE_VAR_X(_1, a); CATCHKIT_INTERNAL_DECLARE_VAR_X(_2, b); CATCHKIT_INTERNAL_DECLARE_VAR_X(_3, c)
#define CATCHKIT_INTERNAL_DECLARE_VARS_4(a, b, c, d) CATCHKIT_INTERNAL_DECLARE_VAR_X(_1, a); CATCHKIT_INTERNAL_DECLARE_VAR_X(_2, b); CATCHKIT_INTERNAL_DECLARE_VAR_X(_3, c); CATCHKIT_INTERNAL_DECLARE_VAR_X(_4, d)

#define CATCHKIT_INTERNAL_DECLARE_VARS_ERROR(...) \
    static_assert(false, \
        "CAPTURE ERROR: Too many variable names provided! " \
        "This macro supports a maximum of 4 variables. " \
        "Consider breaking into multiple CAPTURE calls.")

#define CATCHKIT_INTERNAL_GET_6TH_ARG(arg1, arg2, arg3, arg4, arg5, arg6, ...) arg6
#define CATCHKIT_INTERNAL_DECLARE_VARS_CHOOSER(...) CATCHKIT_INTERNAL_GET_6TH_ARG(__VA_ARGS__, CATCHKIT_INTERNAL_DECLARE_VARS_ERROR, CATCHKIT_INTERNAL_DECLARE_VARS_4, CATCHKIT_INTERNAL_DECLARE_VARS_3, CATCHKIT_INTERNAL_DECLARE_VARS_2, CATCHKIT_INTERNAL_DECLARE_VARS_1)

#define CATCHKIT_INTERNAL_VAR(...) CATCHKIT_INTERNAL_DECLARE_VARS_CHOOSER(__VA_ARGS__)(__VA_ARGS__)
#define CAPTURE(...) CATCHKIT_INTERNAL_VAR(__VA_ARGS__)

// Static assert
#define REQUIRE_STATIC(...) static_assert(__VA_ARGS__)

#define PASS() CATCHKIT_INTERNAL_BOOL_ASSERT( "PASS", check, true )
#define FAIL() CATCHKIT_INTERNAL_BOOL_ASSERT( "FAIL", require, false )


// Packed from catchkit/include/catchkit/checker.h
namespace CatchKit::Detail
{
    class Asserter;
    struct MatchResult;

    enum class InvertResult { No = 0, Yes = 1 };

    struct Checker {
        ResultHandler* result_handler = nullptr;
        bool should_decompose = true;
        std::optional<std::ostringstream> message_stream = {};

        auto check(AssertionContext const& context, InvertResult invert_result=InvertResult::No) -> Asserter;
        auto require(AssertionContext const& context, InvertResult invert_result=InvertResult::No) -> Asserter;
    };

    inline auto to_result_type( ResultType result ) -> ResultType { return result; }
    auto to_result_type( MatchResult const& result ) -> ResultType; // Implemented in internal_matchers.h

    class Asserter {
        Checker& checker;
        InvertResult invert_result = InvertResult::No;

        std::optional<ExpressionInfo> expression_info;

        void report_current_exception() const;
    public:
        explicit Asserter( Checker& checker, InvertResult invert_result );
        ~Asserter() noexcept(false); // NOSONAR NOLINT (misc-typo)

        auto& handle_unexpected_exceptions(std::invocable<Asserter&> auto const& expr_call) {
            try {
                expr_call(*this);
            }
            catch(...) {
                report_current_exception();
            }
            return *this;
        }

        void simple_assert(std::nullptr_t) noexcept {
            simple_assert(false);
        }
        void simple_assert(auto const& result) noexcept {
            if( checker.result_handler->on_assertion_result(!result ? ResultType::Failed : ResultType::Passed) == ResultDetailNeeded::Yes ) {
                expression_info = std::monostate();
            }
        }
        void accept_expr(auto&& expr) noexcept {  // NOSONAR NOLINT (misc-typo)
            auto raw_result = expr.evaluate();
            auto result = to_result_type( raw_result );
            if( invert_result == InvertResult::Yes )
                result = result == ResultType::Failed ? ResultType::Passed : ResultType::Failed;
            if( checker.result_handler->on_assertion_result( result ) == ResultDetailNeeded::Yes ) {
                expression_info = expr.expand( raw_result );
            }
        }

        template<typename ArgT, typename MatcherT>
        constexpr void assert_that( ArgT&& arg, MatcherT&& matcher ) noexcept;

        [[maybe_unused]] friend auto& operator << ( Asserter& asserter, auto&& message ) {
            if( asserter.expression_info ) {
                if( !asserter.checker.message_stream )
                    asserter.checker.message_stream.emplace();
                *asserter.checker.message_stream << message;
            }
            return asserter;
        }

        // To kick off an expression decomposition
        [[maybe_unused]] friend constexpr auto operator <=> ( Asserter const&, auto&& value ) noexcept { // NOSONAR NOLINT (misc-typo)
            return UnaryExprRef{ value };
        }
    };

    // --------------

    template<typename T>
    auto UnaryExprRef<T>::evaluate() const -> ResultType {
        using enum ResultType;
        if constexpr( requires (T v){ { !v } -> std::same_as<bool>; }) {
            CATCHKIT_WARNINGS_SUPPRESS_START
            CATCHKIT_WARNINGS_SUPPRESS_ADDRESS
            CATCHKIT_WARNINGS_SUPPRESS_NULL_CONVERSION
            return !value ? Failed : Passed;
            CATCHKIT_WARNINGS_SUPPRESS_END
        }
        else {
            // Special case for GCC
            static_assert( std::is_null_pointer_v<T> );
            return Failed;
        }
    }
    template<typename T>
    auto UnaryExprRef<T>::expand(ResultType) const -> ExpressionInfo {
        return UnaryExpressionInfo{ stringify(value) };
    }

    CATCHKIT_WARNINGS_SUPPRESS_START
    CATCHKIT_WARNINGS_SUPPRESS_SIGN_MISMATCH
    template<typename LhsT, typename RhsT, Operators Op>
    auto eval_expr(BinaryExprRef<LhsT, RhsT, Op> const& expr) {
        using enum Operators;
        if constexpr( Op == Equals )                    return expr.lhs == expr.rhs;
        else if constexpr( Op == NotEqualTo )           return expr.lhs != expr.rhs;
        else if constexpr( Op == GreaterThan )          return expr.lhs >  expr.rhs;
        else if constexpr( Op == LessThan )             return expr.lhs <  expr.rhs;
        else if constexpr( Op == GreaterThanOrEqual )   return expr.lhs >= expr.rhs;
        else if constexpr( Op == LessThanOrEqual )      return expr.lhs <= expr.rhs;
        else {
            // Note that while None is a valid enum value, we should never use it on a path that leads here
            static_assert( false, "Operator not implemented" );
        }
        std::unreachable();
    }
    CATCHKIT_WARNINGS_SUPPRESS_END

    template<typename LhsT, typename RhsT, Operators Op>
    auto BinaryExprRef<LhsT, RhsT, Op>::evaluate() const -> ResultType {
        return static_cast<bool>( eval_expr(*this) ) ? ResultType::Passed : ResultType::Failed;
    }
    template<typename LhsT, typename RhsT, Operators Op>
    auto BinaryExprRef<LhsT, RhsT, Op>::expand(ResultType) const -> ExpressionInfo {
        return BinaryExpressionInfo{
            std::string( stringify(lhs) ),
            std::string( stringify(rhs) ),
            operator_to_string<Op>() };
    }

} // namespace CatchKit::Detail

namespace CatchKit
{
    using Detail::Checker;

} // namespace CatchKit

// This global instance is used if not using the one passed in to a function locally
extern constinit CatchKit::Checker catch23_checker; // NOSONAR NOLINT (misc-typo)


// Packed from catchkit/include/catchkit/internal_matchers.h
namespace CatchKit {

    namespace Detail {

        struct SubExpression {
            bool result;
            uintptr_t matcher_address;
        };

        // Holds the result of a match
        struct MatchResult {
            bool result;
            uintptr_t matcher_address;

            explicit(false) MatchResult( bool result, uintptr_t matcher_address = 0 ) : result(result), matcher_address(matcher_address) {}
            explicit operator bool() const { return result; }

            template<typename T, typename Self>
            auto&& set_address_of(this Self&& self, T const& object) {
                self.set_address( std::bit_cast<uintptr_t>( &object ) );
                return std::forward<Self>(self);
            }

        private:
            void set_address( uintptr_t address );
        };

        // A match result for composite matchers (with &&, ||, ! and >>)
        struct CompositeMatchResult : MatchResult { // NOSONAR NOLINT (misc-typo)
            std::vector<SubExpression> child_results;

            using MatchResult::MatchResult;
            explicit(false) CompositeMatchResult( MatchResult const& other ) : MatchResult( other ) {}
            CompositeMatchResult( CompositeMatchResult&& other ) = default;

            auto add_children_from( MatchResult const& ) -> CompositeMatchResult&& { return std::move(*this); }
            auto add_children_from( CompositeMatchResult const& other) -> CompositeMatchResult&&;
            auto make_child_of( uintptr_t address ) -> CompositeMatchResult&&;
            auto make_child_of( auto const& matcher ) -> CompositeMatchResult&& { return make_child_of( std::bit_cast<uintptr_t>( matcher ) ); }
        };

        struct MatcherDescription {
            std::string description;

            template<typename T> requires std::is_convertible_v<T, std::string>
            explicit(false) MatcherDescription( T&& description) // NOSONAR NOLINT (misc-typo)
            : description(std::forward<T>( description )) {}
        };

        inline auto to_result_type( MatchResult const& result ) -> ResultType { return result ? ResultType::Passed : ResultType::Failed; }

        struct AlwaysMatcher {
            static auto match(auto&&) -> MatchResult { return true; }
            static auto lazy_match(auto&&) -> MatchResult  { return true; }
        };

        template<typename M>
        concept IsMatcher = requires(M m) {
            { m.describe() } -> std::same_as<MatcherDescription>;
        };

        template<typename M, typename T>
        concept IsEagerMatcher = requires(M m, T arg) {
            { m.match(arg) } -> std::convertible_to<MatchResult>;
        };

        template<typename M, typename T>
        concept IsLazyMatcher = requires(M m, T(*f)()) {
            { m.lazy_match(f) } -> std::convertible_to<MatchResult>;
        };

        template<typename M, typename T>
        concept IsEagerBindableMatcher = requires(M m, T arg, AlwaysMatcher matcher) {
            { m.match(arg, matcher) } -> std::convertible_to<MatchResult>;
        };

        template<typename M, typename T>
        concept IsLazyBindableMatcher = requires(M m, T(*f)(), AlwaysMatcher matcher) {
            { m.lazy_match(f, matcher) } -> std::convertible_to<MatchResult>;
        };

        template<typename M>
        concept IsCompositeMatcher = requires {
            typename std::remove_cvref_t<M>::ComposedMatcher1;
        };

        template<typename M>
        concept IsBinaryCompositeMatcher = requires {
            typename M::ComposedMatcher1;
            typename M::ComposedMatcher2;
        };

        template<typename M>
        concept IsUnaryCompositeMatcher = IsCompositeMatcher<M> && !IsBinaryCompositeMatcher<M>;

        template<typename MatcherT>
        constexpr void enforce_composite_matchers_are_rvalues() {
            static_assert(!IsCompositeMatcher<MatcherT> || !std::is_lvalue_reference_v<MatcherT>,
                "Composite Matchers (&&, ||, !) cannot be stored in variables. Use them inline");
        }


        template<typename ArgT, typename MatcherT>
        auto invoke_matcher( MatcherT& matcher, ArgT&& arg ) {
            if constexpr( std::invocable<ArgT> ) {
                using ReturnedArgType = decltype(arg());
                if constexpr( IsLazyMatcher<MatcherT, ReturnedArgType> ) {
                    return matcher.lazy_match( arg ).set_address_of( matcher );
                }
                else {
                    static_assert( IsEagerMatcher<MatcherT, ReturnedArgType> );
                    return matcher.match( arg() ).set_address_of( matcher );
                }
            }
            else {
                static_assert( IsEagerMatcher<MatcherT, ArgT> );
                return matcher.match( arg ).set_address_of( matcher );
            }
        }


        // The result of a && expression
        template<typename M1, typename M2>
        struct AndMatcher {
            using ComposedMatcher1 = M1;
            using ComposedMatcher2 = M2;
            M1& matcher1;
            M2& matcher2;

            auto match( auto const& value ) const -> CompositeMatchResult {
                auto result1 = CompositeMatchResult( invoke_matcher( matcher1, value ) ).make_child_of(this);
                if( !result1 )
                    return result1; // Short circuit
                return CompositeMatchResult(invoke_matcher( matcher2, value ))
                    .make_child_of(this) // Create new matcher for this level
                    .add_children_from(result1); // add in the other result

            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("({} && {})", matcher1.describe().description, matcher2.describe().description);
            }
        };

        // The result of a || expression
        template<typename M1, typename M2>
        struct OrMatcher {
            using ComposedMatcher1 = M1;
            using ComposedMatcher2 = M2;
            M1& matcher1;
            M2& matcher2;

            auto match( auto const& value ) const -> CompositeMatchResult {
                auto result1 = CompositeMatchResult( invoke_matcher(matcher1, value) )
                    .make_child_of(this);
                if( result1 )
                    return result1; // Short circuit
                return CompositeMatchResult( invoke_matcher( matcher2,  value ) )
                    .make_child_of(this) // Create new matcher for this level
                    .add_children_from(result1); // add in the other result
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("({} || {})", matcher1.describe().description, matcher2.describe().description);
            }
        };

        // The result of a ! expression
        template<typename M>
        struct NotMatcher {
            using ComposedMatcher1 = M;
            M& base_matcher;

            auto match( auto const& value ) const -> CompositeMatchResult {
                return match_common( value );
            }
            auto lazy_match( auto const& value ) const -> CompositeMatchResult {
                return match_common( value );
            }
            auto match_common( auto const& value ) const -> CompositeMatchResult {
                auto result = CompositeMatchResult( invoke_matcher( base_matcher, value ) )
                    .make_child_of(this);
                result.result = !result.result;
                return result;

            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("!({})", base_matcher.describe().description);
            }
        };

        template<IsMatcher M1, typename M2>
        auto operator && ( M1&& m1, M2&& m2 ) { // NOSONAR NOLINT (misc-typo)
            enforce_composite_matchers_are_rvalues<M1>();
            enforce_composite_matchers_are_rvalues<M2>();
            static_assert(IsMatcher<M2>, "Operand to && is not a matcher");
            return AndMatcher(m1, m2);
        }

        template<IsMatcher M1, typename M2>
        auto operator || ( M1&& m1, M2&& m2 ) { // NOSONAR NOLINT (misc-typo)
            enforce_composite_matchers_are_rvalues<M1>();
            enforce_composite_matchers_are_rvalues<M2>();
            static_assert(IsMatcher<M2>, "Operand to || is not a matcher");
            return OrMatcher( m1, m2 );
        }

        template<IsMatcher MatcherT>
        auto operator ! (MatcherT&& m) { // NOSONAR NOLINT (misc-typo)
            enforce_composite_matchers_are_rvalues<MatcherT>();
            return NotMatcher(m);
        }

        // Matchers may be monadically bound with the >>= operator.
        // If so, the left operand must implement match(arg, bound_matcher)
        template<typename M1, typename M2>
        struct BoundMatchers {
            using ComposedMatcher1 = M1;
            using ComposedMatcher2 = M2;
            M1 matcher1;
            M2 matcher2;

            template<typename ArgT>
            auto lazy_match( ArgT const& arg ) const -> CompositeMatchResult {
                if constexpr ( IsLazyBindableMatcher<M1, ArgT> ) {
                    static_assert( std::invocable<ArgT>, "Lazy matchers must be matched against lambdas" );
                    return matcher1.lazy_match(arg, matcher2)
                        .set_address_of( matcher1 )
                        .make_child_of(this);
                }
                else
                    return match(arg);
            }

            template<typename ArgT>
            auto match( ArgT const& arg ) const -> CompositeMatchResult {
                static_assert( IsEagerBindableMatcher<M1, ArgT>, "The LHS of >>= must be a bindable matcher" );
                if constexpr( std::invocable<ArgT> )
                    return CompositeMatchResult( matcher1.match(arg(), matcher2) )
                        .set_address_of( matcher1 )
                        .make_child_of(this);
                else
                    return CompositeMatchResult( matcher1.match(arg, matcher2) )
                        .set_address_of( matcher1 )
                        .make_child_of(this);
            }

            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("({} >>= {})", matcher1.describe().description, matcher2.describe().description);
            }
        };

        template<IsMatcher M1, typename M2>
        auto operator >>= ( M1&& m1, M2&& m2 ) {
            static_assert(IsMatcher<M2>, "Operand to >>= is not a matcher");
            return BoundMatchers{std::forward<M1>(m1), std::forward<M2>(m2)};
        }

        void add_subexpressions( std::vector<SubExpressionInfo>& sub_expressions, CompositeMatchResult const& results, uintptr_t matcher_address, std::string const& description );

        template<typename M>
        auto collect_subexpressions(M const& matcher, std::vector<SubExpressionInfo>& sub_expressions, CompositeMatchResult const& results) {
            if constexpr( IsBinaryCompositeMatcher<M> ) {
                collect_subexpressions(matcher.matcher1, sub_expressions, results);
                collect_subexpressions(matcher.matcher2, sub_expressions, results);
            }
            else if constexpr( IsUnaryCompositeMatcher<M> ) {
                collect_subexpressions(matcher.base_matcher, sub_expressions, results);
            }
            else {
                add_subexpressions( sub_expressions, results, std::bit_cast<uintptr_t>(&matcher), matcher.describe().description );
            }
        }

        template<typename ArgT, typename MatcherT>
        struct MatchExprRef {
            ArgT& arg;
            MatcherT const& matcher;

            [[nodiscard]] auto evaluate() const {
                return invoke_matcher( matcher, arg );
            }
            [[nodiscard]] auto arg_as_string() const -> std::string {
                try {
                    if constexpr ( !std::invocable<ArgT> )
                        return stringify(arg);
                    else if constexpr (!std::is_void_v<decltype(arg())>)
                        return stringify(arg());
                    else
                        return {};
                }
                catch(...) {
                    return std::format("exception thrown while evaluating matcher: {}", get_current_exception_message() );
                }
            }
            [[nodiscard]] auto expand( MatchResult const& ) const -> ExpressionInfo {
                return MatchExpressionInfo{ arg_as_string(), matcher.describe().description, {} };
            }
            [[nodiscard]] auto expand( CompositeMatchResult const& result ) const -> ExpressionInfo {
                std::vector<SubExpressionInfo> sub_expressions;
                if constexpr ( IsCompositeMatcher<MatcherT>) {
                    collect_subexpressions(matcher, sub_expressions, result);
                }
                return MatchExpressionInfo{ arg_as_string(), matcher.describe().description, std::move(sub_expressions) };
            }
        };


        template<typename ArgT, typename MatcherT>
        constexpr void Asserter::assert_that( ArgT&& arg, MatcherT&& matcher ) noexcept { // NOSONAR (we use the ref in its lifetime) NOLINT (misc-typo)
            enforce_composite_matchers_are_rvalues<MatcherT>();
            accept_expr( MatchExprRef{ arg, matcher } );
        }

    } // namespace Detail

    namespace Matchers {

        using Detail::operator &&;
        using Detail::operator ||;
        using Detail::operator !;
        using Detail::operator >>=;

    } // namespace Matchers

    using Detail::MatchResult;
    using Detail::CompositeMatchResult;
    using Detail::MatcherDescription;

} // namespace CatchKit


// Packed from catchkit/include/catchkit/internal_platform.h
#if defined(WIN32) || defined(__WIN32__) || defined(_WIN32) || defined(_MSC_VER) || defined(__MINGW32__)
#  define CATCHKIT_PLATFORM_WINDOWS
#else
#  define CATCHKIT_PLATFORM_POSIX
#  if defined(linux) || defined(__linux) || defined(__linux__)
#    define CATCHKIT_PLATFORM_LINUX
#  elifdef __APPLE__
#    define CATCHKIT_PLATFORM_APPLE
#    include <TargetConditionals.h>
#    if TARGET_OS_OSX == 1
#      define CATCHKIT_PLATFORM_MAC
#    elif TARGET_OS_IPHONE == 1
#      define CATCHKIT_PLATFORM_IPHONE
#    endif
#  elif defined(linux) || defined(__linux) || defined(__linux__)
#    define CATCHKIT_PLATFORM_LINUX
#  endif
#endif


// Packed from catchkit/include/catchkit/matchers.h
namespace CatchKit {

    template<class T>
    concept IsStringViewable = std::is_convertible_v<T, std::string_view>;

    template<class T>
    concept NotStringViewable = !std::is_convertible_v<T, std::string_view>;

    template<class T>
    concept NonStringRange = NotStringViewable<T> && std::ranges::sized_range<T>;

    template<class T>
    concept NotARange = NotStringViewable<T> && !std::ranges::sized_range<T>;


    namespace GenericMatchers {
        template<typename T>
        struct Equals {
            T& match_value;

            [[nodiscard]] constexpr auto match(std::remove_const_t<T>& value) const -> MatchResult {
                return value == match_value;
            }
            [[nodiscard]] constexpr auto match(T const& value) const -> MatchResult {
                return value == match_value;
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("equals( {} )", stringify(match_value));
            }
        };

        struct HasSize {
            std::size_t size;

            [[nodiscard]] auto match(auto&& val) const -> MatchResult { // NOSONAR NOLINT(misc-type)
                return std::size(val) == size;
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("has_size(\"{}\")", size);
            }
        };

        template<typename PredicateT>
        struct MatchesPredicate {
            PredicateT pred;
            std::string description;

            explicit MatchesPredicate( PredicateT&& pred, std::string description )
            : pred( std::move(pred) ), description( std::move(description) ) {}

            [[nodiscard]] auto match( auto const& arg ) const -> MatchResult {
                return pred(arg);
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return description;
            }
        };
    }

    namespace RangeMatchers {

        struct InOrder {
            static auto equals(auto const& range1, auto const& range2 ) {
                if( std::size(range1) != std::size(range2) )
                    return false;
                for( const auto& [e1, e2] : std::views::zip(range1, range2) )
                    if( e1 != e2 )
                        return false;
                return true;
            }
        };
        struct InAnyOrder {
            static auto equals(auto const& range1, auto const& range2 ) {
                auto set = range2 | std::ranges::to<std::unordered_set>();
                for( const auto& match_element : range1 )
                    if( set.erase(match_element) == 0 )
                        return false;
                return set.empty();
            }
        };

        template<typename T>
        struct ContainsElement {
            T const& element;

            template<typename Range>
            [[nodiscard]] auto match(Range const& range) const -> MatchResult {
                static_assert(std::ranges::sized_range<Range>);
                for( const auto& match_element : range ) {
                    if( element == match_element )
                        return true;
                }
                return false;
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("contains({})", stringify(element));
            }
        };

        template<typename R>
        struct ContainsRange {
            R const& range;

            template<typename Range>
            [[nodiscard]] auto match(Range const& match_range) const -> MatchResult {
                static_assert(std::ranges::sized_range<Range>);
                auto set = range | std::ranges::to<std::unordered_set>();
                for( const auto& match_element : match_range )
                    set.erase(match_element);
                return set.empty();
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("contains({})", stringify(range));
            }
        };

        template<typename OrderPolicy, typename R>
        struct Equals {
            R const& range;

            template<typename Range>
            [[nodiscard]] auto match(Range const& match_range) const -> MatchResult {
                static_assert(std::ranges::sized_range<Range>);
                return OrderPolicy::equals(range, match_range);
            }

            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("equals({})", stringify(range));
            }
        };
    }


    namespace StringMatchers {

        struct CaseSensitive {
            static constexpr std::string name = "CaseSensitive";
            static bool equal(std::string_view str1, std::string_view str2);
            static bool find(std::string_view str, std::string_view substr);
            static bool matches_regex(std::string const& str, std::string const& regex_str);
        };
        struct CaseInsensitive {
            static constexpr std::string name = "CaseInsensitive";
            static bool equal(std::string_view str1, std::string_view str2);
            static bool find(std::string_view str, std::string_view substr);
            static bool matches_regex(std::string const& str, std::string const& regex_str);
        };

        template<typename CasePolicy=CaseSensitive>
        struct StartsWith {
            std::string_view match_str;

            [[nodiscard]] auto match(std::string_view str) const -> MatchResult {
                if( match_str.size() > str.size() )
                    return false;
                return CasePolicy::equal(str.substr(0, match_str.size()), match_str);
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("starts_with<{}>(\"{}\")", CasePolicy::name, match_str);
            }
        };
        template<typename CasePolicy=CaseSensitive>
        struct EndsWith {
            std::string_view match_str;

            [[nodiscard]] auto match(std::string_view str) const -> MatchResult {
                if( match_str.size() > str.size() )
                    return false;
                return CasePolicy::equal(str.substr(str.size()-match_str.size()), match_str);
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("ends_with<{}>(\"{}\")", CasePolicy::name, match_str);
            }
        };
        template<typename CasePolicy=CaseSensitive>
        struct Contains {
            std::string_view match_str;
            [[nodiscard]] auto match( IsStringViewable auto const& str ) const -> MatchResult {
                return CasePolicy::find(str, match_str);
            }
            [[nodiscard]] auto match( NonStringRange auto const& range ) const -> MatchResult {
                // Special case where we are matching a string, but when contained within a range
                for( const auto& element : range ) {
                    if( CasePolicy::equal( match_str, element ) )
                        return true;
                }
                return false;
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("contains<{}>(\"{}\")", CasePolicy::name, match_str);
            }
        };

        template<typename CasePolicy=CaseSensitive>
        struct Equals {
            std::string_view match_str;

            [[nodiscard]] auto match(std::string_view str) const -> MatchResult {
                return CasePolicy::equal(str, match_str);
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("equals<{}>(\"{}\")", CasePolicy::name, match_str);
            }
        };


        template<typename CasePolicy=CaseSensitive>
        struct MatchesRegex {
            std::string regex_str;

            [[nodiscard]] auto match(std::string const& str) const -> MatchResult {
                return CasePolicy::matches_regex(str, regex_str);
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("matches_regex<{}>(\"{}\")", CasePolicy::name, regex_str);
            }
        };

    } // namespace StringMatchers

    namespace ExceptionMatchers {

        struct HasMessage {
            std::optional<std::string> what;

            [[nodiscard]] auto match(auto const& ex) const -> MatchResult {
                return what ? Detail::get_exception_message(ex) == *what : true;
            }
            template<typename BoundMatcherT>
            [[nodiscard]] auto match(auto const& ex, BoundMatcherT const& bound_matcher ) const -> CompositeMatchResult {
                static_assert(Detail::IsEagerMatcher<BoundMatcherT, std::string>);

                std::string message = Detail::get_exception_message(ex);
                if( what && message != *what )
                    return false;

                return CompositeMatchResult( bound_matcher.match(message) )
                    .set_address_of( bound_matcher )
                    .make_child_of( this );
            }

            [[nodiscard]] auto describe() const -> MatcherDescription {
                if( what )
                    return std::format("has_message(\"{}\")", *what);
                else
                    return std::format("has_message()");
            }
        };

        template<typename E=void>
        struct Throws {
            template<Detail::IsEagerMatcher<std::string> MessageMatcher>
            auto constexpr with_message_that( MessageMatcher const& message_matcher ) {
                using Detail::operator >>=;
                return *this >>= HasMessage() >>= message_matcher;
            }
            auto constexpr with_message( std::string_view message_to_match ) {
                using Detail::operator >>=;
                return *this >>= HasMessage() >>= StringMatchers::Equals{ message_to_match };
            }

            template<typename ArgT>
            [[nodiscard]] constexpr auto lazy_match(ArgT&& f) const -> CompositeMatchResult {
                return lazy_match(std::forward<ArgT>(f), Detail::AlwaysMatcher()).make_child_of(this);
            }

            template<typename BoundMatcherT>
            [[nodiscard]] constexpr auto lazy_match(auto&& f, BoundMatcherT const& bound_matcher) const -> CompositeMatchResult {
                if constexpr( std::is_void_v<E> ) {
                    try {
                        f();
                        return false;
                    }
                    catch(...) {
                        return CompositeMatchResult( bound_matcher.match(std::current_exception()) )
                            .set_address_of( bound_matcher )
                            .make_child_of(this);
                    }
                }
                else {
                    static_assert(Detail::IsEagerMatcher<BoundMatcherT, E>,
                        "The bound matcher must accept the type (or a super class of) that was detected as thrown");
                    try {
                        f();
                        return false;
                    }
                    catch(E& ex) {
                        return CompositeMatchResult( bound_matcher.match(ex) )
                            .set_address_of( bound_matcher )
                            .make_child_of( this );
                    }
                    catch(...) {
                        return false;
                    }
                }
                return false;
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                if constexpr(std::is_void_v<E>)
                    return "throws()";
                else
                    return std::format("throws<{}>()", type_to_string<E>());
            }
        };

    } // namespace ExceptionMatchers

    namespace FloatMatchers {
        inline auto margin_compare( double lhs, double rhs, double margin ) -> bool {
            return (lhs + margin >= rhs) && (rhs + margin >= lhs);
        }

        struct IsCloseToRel {
            double target;
            double epsilon;

            [[nodiscard]] auto match( double value ) const -> MatchResult {
                if( epsilon < 0 || epsilon >= 1 )
                    throw std::domain_error( "epsilon must be positive and < 1" );
                auto rel_margin = epsilon * (std::max)(std::fabs(value), std::fabs(target));
                return margin_compare( value, target, std::isinf(rel_margin) ? 0 : rel_margin );
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("is_close_to({})", target);
            }
        };

        template<std::floating_point T>
        struct IsCloseToAbs {
            T target;
            double margin;

            [[nodiscard]] auto match(T value) const -> MatchResult {
                if( margin < 0 )
                    throw std::domain_error( "margin must be positive" );
                return margin_compare( value, target, margin );
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("is_close_to_abs({})", target);
            }
        };

        template<std::floating_point T>
        struct IsWithinUlp {
            T target;
            std::uint64_t ulps;

            static constexpr T infinity = std::numeric_limits<T>::infinity();

            [[nodiscard]] auto match(T value) const -> MatchResult {
                if constexpr( std::same_as<T, float> ) {
                    if( ulps >= (std::numeric_limits<std::uint32_t>::max)())
                        throw std::domain_error( "ulps is too large for a float" );
                }
                return value == target ||
                    ( std::nextafter( target, infinity )*ulps >= value &&
                    std::nextafter( target, -infinity )*ulps <= value );
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("is_within_ulp( {} )", target);
            }
        };

        struct IsNaN {
            [[nodiscard]] auto match(std::floating_point auto value) const -> MatchResult {
                return std::isnan( value );
            }
            [[nodiscard]] auto describe() const -> MatcherDescription {
                return std::format("is_nan()");
            }
        };
    } // namespace FloatMatchers


    namespace Matchers {
        using StringMatchers::CaseSensitive;
        using StringMatchers::CaseInsensitive;
        using RangeMatchers::InOrder;
        using RangeMatchers::InAnyOrder;

        auto equals(NotARange auto& value) { return GenericMatchers::Equals{value}; }

        inline auto has_size(std::size_t size) { return GenericMatchers::HasSize{size}; }

        template<typename CasePolicy=CaseSensitive>
        auto starts_with(std::string_view str) { return StringMatchers::StartsWith<CasePolicy>{str}; }

        template<typename CasePolicy=CaseSensitive>
        auto ends_with(std::string_view str) { return StringMatchers::EndsWith<CasePolicy>{str}; }

        template<typename CasePolicy=CaseSensitive>
        auto contains(IsStringViewable auto const& str) {
            return StringMatchers::Contains<CasePolicy>{ std::string_view(str) };
        }

        auto contains(NotARange auto const& element) {
            return RangeMatchers::ContainsElement{ element };
        }

        auto contains(NotStringViewable auto const& range) {
            return RangeMatchers::ContainsRange{ range };
        }

        template<typename OrderPolicy = InOrder, NonStringRange R>
        auto equals( R const& range ) {
            return RangeMatchers::Equals<OrderPolicy, R>{ range };
        }

        template<typename CasePolicy=CaseSensitive>
        auto equals(std::string_view str) { return StringMatchers::Equals<CasePolicy>{str}; }

        template<typename CasePolicy=CaseSensitive>
        auto matches_regex(std::string str) { return StringMatchers::MatchesRegex<CasePolicy>{ std::move(str) }; }

        template<std::floating_point T>
        auto is_close_to(T target, double margin = 100*std::numeric_limits<T>::epsilon() ) {
            return FloatMatchers::IsCloseToAbs{ target, margin };
        }
        template<std::floating_point T>
        auto is_close_to_rel( T target, double epsilon = 100*std::numeric_limits<T>::epsilon() ) {
            return FloatMatchers::IsCloseToRel{ target, epsilon };
        }
        auto is_within_ulp(std::floating_point auto target, std::uint64_t ulps=1) {
            return FloatMatchers::IsWithinUlp{ target, ulps };
        }
        inline auto is_nan() {
            return FloatMatchers::IsNaN();
        }

        inline auto is_true() { static bool true_value = true; return equals(true_value); }
        inline auto is_false() { static bool false_value = false; return equals(false_value); }


        template<typename E=void>
        using throws = ExceptionMatchers::Throws<E>;

        template<typename PredicateT>
        auto matches_predicate(PredicateT&& pred, std::string description = "predicate") {
            return GenericMatchers::MatchesPredicate<PredicateT>(std::forward<PredicateT>(pred), std::move(description));
        }

    } // namespace Matchers

} // namespace CatchKit

// From source files:
#ifdef CATCHKIT_IMPL

// System includes (for impl):
#include <algorithm>
#include <print>
#include <regex>


// Packed from catchkit/src/assert_result_handler.cpp
namespace CatchKit::Detail {

    void AssertResultHandler::on_assertion_start( ResultDisposition result_disposition, AssertionContext const& context ) {
        current_context = context;
        current_result_disposition = result_disposition;
    }

    auto AssertResultHandler::on_assertion_result( ResultType result ) -> ResultDetailNeeded {
        last_result = result;
        if( last_result == ResultType::Passed )
            return ResultDetailNeeded::No;
        return ResultDetailNeeded::Yes;
    }
    void AssertResultHandler::on_assertion_result_detail( ExpressionInfo const& expression_info, std::string_view message ) {
        // !TBD When we can use stacktrace do something like this:
        // https://godbolt.org/z/jM4TnaMEW

        // Redundant?
        auto os = stdout;
        if (last_result != ResultType::Passed )
            os = stderr;

        std::println(os, "{}:{}:{}: in function '{}'",
                current_context.location.file_name(),
                current_context.location.line(),
                current_context.location.column(),
                current_context.location.function_name());
        std::string_view macro_name = current_context.macro_name;
        if ( macro_name.empty() )
            macro_name = "assertion";
        if ( !current_context.original_expression.empty() )
            std::println(os, "{} {} for expression:\n\t{}",
                macro_name, (last_result == ResultType::Passed) ? "passed" : "failed",
                current_context.original_expression);
        else
            std::println(os, "{} {}",
                macro_name, (last_result == ResultType::Passed) ? "passed" : "failed");

        if( last_result == ResultType::Failed ) {
            if( auto except_expr = std::get_if<ExceptionExpressionInfo>( &expression_info ) ) {
                switch( except_expr->type ) {
                    case ExceptionExpressionInfo::Type::Missing:
                        std::println(os, "due to a missing exception");
                        break;
                case ExceptionExpressionInfo::Type::Unexpected:
                    std::println(os, "due to an unexpected exception");
                    break;
                default:
                    assert( false );
                }
            }
        }
        if(!std::holds_alternative<std::monostate>(expression_info))
            std::println(os, "with expansion:\n\t{}", expression_info );

        if (!message.empty()) {
            std::println(os, "with message:\n\t{}", message);
        }
    }
    void AssertResultHandler::on_assertion_end() {
        if ( last_result != ResultType::Passed && current_result_disposition == ResultDisposition::Abort ) {
            std::terminate();
        }
    }

} // namespace CatchKit::Detail

// Packed from catchkit/src/checker.cpp
namespace {
    CatchKit::Detail::AssertResultHandler default_assertion_handler; // NOSONAR NOLINT (misc-typo)
}

constinit CatchKit::Checker catch23_checker{ &default_assertion_handler }; // NOSONAR NOLINT (misc-typo)

namespace CatchKit::Detail {

    auto Checker::check(AssertionContext const& context, InvertResult invert_result) -> Asserter {
        result_handler->on_assertion_start(ResultDisposition::Continue, context);
        return Asserter( *this, invert_result );
    }
    auto Checker::require(AssertionContext const& context, InvertResult invert_result) -> Asserter {
        result_handler->on_assertion_start(ResultDisposition::Abort, context);
        return Asserter( *this, invert_result );
    }

    Asserter::Asserter( Checker& checker, InvertResult invert_result ) : checker(checker), invert_result(invert_result) {
        if( checker.message_stream )
            checker.message_stream->clear();
    }
    Asserter::~Asserter() noexcept(false) {
        if( expression_info ) {
            if( checker.message_stream )
                checker.result_handler->on_assertion_result_detail( *expression_info, checker.message_stream->str() );
            else
                checker.result_handler->on_assertion_result_detail( *expression_info, {} );
        }

        checker.result_handler->on_assertion_end(); // This may throw to cancel the test
    }

    void Asserter::report_current_exception() const {
        if( checker.result_handler->on_assertion_result(ResultType::Failed) == ResultDetailNeeded::Yes ) {
            checker.result_handler->on_assertion_result_detail(
                ExceptionExpressionInfo{
                    get_exception_message(
                        std::current_exception()),
                        ExceptionExpressionInfo::Type::Unexpected },
                    {} );
        }
    }


} // namespace CatchKit::Detail

// Packed from catchkit/src/exceptions.cpp
namespace CatchKit::Detail {

    const std::string unknown_exception_message = "<unknown exception type>";

    [[nodiscard]] auto get_exception_message( std::exception const& ex ) -> std::string {
        return ex.what();
    }
    [[nodiscard]] auto get_exception_message( std::string const& str ) -> std::string {
        return str;
    }

    [[nodiscard]] auto get_exception_message( std::exception_ptr const& ex ) -> std::string {
        std::string message;
        try {
            std::rethrow_exception(ex);
        }
        catch(std::exception& e) { // NOSONAR NOLINT (misc-typo)
            return get_exception_message(e);
        }
        catch (std::string& s) {
            return get_exception_message(s);
        }
        catch(...) { // NOSONAR NOLINT (misc-typo)
            // !TBD: registry for custom exception translations
            return unknown_exception_message;
        }
    }
    [[nodiscard]] auto get_current_exception_message() -> std::string {
        return get_exception_message(std::current_exception());
    }

} // namespace CatchKit::Detail
// Packed from catchkit/src/expression_info.cpp
std::format_context::iterator std::formatter<CatchKit::ExpressionInfo>::format(CatchKit::ExpressionInfo const& expr, std::format_context& ctx) {
    using namespace CatchKit;

    return std::visit(
        [&]<typename T>(T const& expr_inner) -> std::format_context::iterator {
            if constexpr(std::is_same_v<T, UnaryExpressionInfo>)
                return std::format_to( ctx.out(), "{}", expr_inner.value );
            if constexpr(std::is_same_v<T, BinaryExpressionInfo>)
                return std::format_to( ctx.out(), "{} {} {}", expr_inner.lhs, expr_inner.op, expr_inner.rhs );
            if constexpr(std::is_same_v<T, MatchExpressionInfo>)
                return std::format_to( ctx.out(), "{} {}", expr_inner.candidate_value, expr_inner.matcher );
            if constexpr(std::is_same_v<T, ExceptionExpressionInfo>)
                return std::format_to( ctx.out(), "{}", expr_inner.exception_message );
            assert(false);
    }, expr);
}

// Packed from catchkit/src/internal_matchers.cpp
namespace CatchKit::Detail {

    void MatchResult::set_address( uintptr_t address ) {
        assert(matcher_address == 0 || matcher_address == address);
        matcher_address = address;
    }

    auto CompositeMatchResult::add_children_from(CompositeMatchResult const& other) -> CompositeMatchResult&& {
        child_results.reserve( child_results.size() + other.child_results.size() );
        std::ranges::copy( other.child_results, std::back_inserter( child_results ) );
        return std::move(*this);
    }

    auto CompositeMatchResult::make_child_of(uintptr_t address) -> CompositeMatchResult&& {
        child_results.emplace_back( result, std::exchange( matcher_address, address ) );
        return std::move(*this);
    }

} // namespace CatchKit::Detail
// Packed from catchkit/src/matchers.cpp
namespace CatchKit {

    // !TBD: test the others
    static_assert(Detail::IsMatcher<GenericMatchers::Equals<bool>>);
    static_assert(Detail::IsEagerMatcher<ExceptionMatchers::HasMessage, std::domain_error>);
    static_assert(Detail::IsMatcher<ExceptionMatchers::HasMessage>);
    static_assert( Detail::IsCompositeMatcher<Detail::AndMatcher<GenericMatchers::Equals<bool>, GenericMatchers::Equals<bool>>> );

    namespace StringMatchers {

        bool CaseSensitive::equal(std::string_view str1, std::string_view str2) {
            return str1 == str2;
        }
        bool CaseSensitive::find(std::string_view str, std::string_view substr) {
            return str.contains(substr);
        }
        bool CaseInsensitive::equal(std::string_view str1, std::string_view str2) {
            return std::ranges::equal(str1, str2,
                [](char a, char b) {
                    return std::tolower(a) == std::tolower(b);
                });
        }
        bool CaseInsensitive::find(std::string_view str, std::string_view substr) {
            return !std::ranges::search(str, substr,
                [](char a, char b) {
                    return std::tolower(a) == std::tolower(b);
                }).empty();
        }

        bool CaseSensitive::matches_regex(std::string const& str, std::string const& regex_str) {
            return std::regex_match(str, std::regex(regex_str));
        }
        bool CaseInsensitive::matches_regex(std::string const& str, std::string const& regex_str) {
            return std::regex_match(str, std::regex(regex_str, std::regex::icase));
        }

    } // namespace StringMatchers

    namespace Detail {
        void add_subexpressions( std::vector<SubExpressionInfo>& sub_expressions, CompositeMatchResult const& results, uintptr_t matcher_address, std::string const& description ) {
            if( auto it = std::ranges::find( results.child_results, matcher_address, &SubExpression::matcher_address ); it != results.child_results.end() )
                sub_expressions.emplace_back(description, it->result);
        }
    } // namespace Detail

} // namespace CatchKit
// Packed from catchkit/src/reflection.cpp
namespace CatchKit::Detail {

    auto parse_templated_name_from_function_name( std::string const& templated_name, std::string_view function_name ) -> std::string_view {
        if( auto start = function_name.find(templated_name + " = "); start != std::string_view::npos ) {
            start += templated_name.size() + 3;
            if( auto end = function_name.find_first_of("];", start); end != std::string_view::npos )
                return function_name.substr(start, end-start);
        }
        return {};
    }
    auto parse_templated_name( std::string const& templated_name, std::source_location location ) -> std::string_view {
        return parse_templated_name_from_function_name( templated_name, location.function_name() );
    }
    auto remove_qualification(std::string_view qualified_name) -> std::string_view {
        if( auto last_colon = qualified_name.find_last_of(':'); last_colon != std::string_view::npos )
            return qualified_name.substr(last_colon+1);
        return qualified_name; // NOLINT
    }

    auto normalise_type_name(std::string_view type_name) -> std::string {
        if( type_name.starts_with("std::") ) {
            auto substr = type_name.substr(5);
            if( auto pos = substr.find( "basic_" ); pos != std::string_view::npos ) {
                substr = substr.substr(pos+6);
                if( substr.starts_with( "string<wchar_t>" ) )
                    return "std::wstring";
                if( substr.starts_with( "string_view<wchar_t>" ) )
                    return "std::wstring_view";

                if( substr.starts_with( "string<char8_t>" ) )
                    return "std::u8string";
                if( substr.starts_with( "string_view<char8_t>" ) )
                    return "std::u8string_view";

                if( substr.starts_with( "string<char16_t>" ) )
                    return "std::u16string";
                if( substr.starts_with( "string_view<char16_t>" ) )
                    return "std::u16string_view";
            }
        }
        return std::string(type_name);
    }

} // namespace CatchKit::Detail

// Packed from catchkit/src/result_handler.cpp
namespace CatchKit::Detail
{
    ResultHandler::~ResultHandler() = default;

} // namespace CatchKit::Detail
// Packed from catchkit/src/stringify.cpp
namespace CatchKit {
    auto pointer_to_string( std::uintptr_t p ) -> std::string {
        return std::format("{:#x}", p);
    }
    auto member_pointer_to_string(void const* p, std::size_t size) -> std::string {
        auto bytes = static_cast<unsigned char const*>(p);

        std::string result = "0x";
        for (size_t i = 0; i < size; ++i)
            result += std::format("{:02x}", bytes[i]);
        return result;
    }
}

// Packed from catchkit/src/variable_capture_ref.cpp
namespace CatchKit::Detail {

    VariableCaptureRef::VariableCaptureRef(std::string_view name, std::string_view type, Checker& checker)
    : name(name), type(type), result_handler(*checker.result_handler) {
        result_handler.add_variable_capture(this);
    }
    VariableCaptureRef::~VariableCaptureRef() {
        result_handler.remove_variable_capture(this);
    }

} // namespace CatchKit::Detail
#endif // CATCHKIT_IMPL

#endif // CATCHKIT_PACKED_H_INCLUDED
