//
// Created by Phil Nash on 21/07/2025.
//

#ifndef CATCHKIT_UNIQUE_NAME_H
#define CATCHKIT_UNIQUE_NAME_H

#define CATCHKIT_INTERNAL_UNIQUE_NAME_CAT2( first, second ) first##second
#define CATCHKIT_INTERNAL_UNIQUE_NAME_CAT( first, second ) CATCHKIT_INTERNAL_UNIQUE_NAME_CAT2( first, second )
#define CATCHKIT_INTERNAL_UNIQUE_NAME( name ) CATCHKIT_INTERNAL_UNIQUE_NAME_CAT( name, __LINE__ )


#endif // CATCHKIT_UNIQUE_NAME_H
